config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :projects
  resources :issues

  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  validates :project_id, :title, :url, :github_issue_id, presence: true

  belongs_to :project
  has_and_belongs_to_many :languages

  def self.search(search_language)
    language = Language.find_by(name: search_language)
    language.present? ? language.issues : []
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_and_belongs_to_many :issues
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :url, :description, presence: true

  has_many :issues

  def path
    project_path = URI.parse(self.url).path
    project_path.slice!(0) if project_path[0] == "/"
    project_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @language_names = Language.all.pluck(:name).sort
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  def index
    @issues = Issue.search(params[:language_name])
    @search_language = params[:language_name]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @issues = @project.issues
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.haml
#home
  %h1= "Start contributing to Open Source projects today!"

  .language-list
    %h2= "Find beginner friendly issues in"

    - @language_names.each do |language_name|
      = link_to language_name, issues_path(language_name: language_name)

  .info.col-xs-12.col-sm-12.col-md-12.col-lg-12
    .contributor.col-xs-12.col-sm-6.col-md-6.col-lg-6
      %button.btn.btn-default.col-xs-7.col-xs-offset-5
        = "I'm a beginner. How do I start?"

    .maintainer.col-xs-12.col-sm-6.col-md-6.col-lg-6
      %button.btn.btn-default.col-xs-7
        = "I'm a maintainer. How can I help?"

app/views/issues/_issue.html.haml
- case view

- when :index_project
  .issue-listed
    %h4.issue-title= issue.title

- when :index_language
  .issue-listed
    %h4.issue-title= issue.title
    %p= issue.project.name

app/views/issues/index.html.haml
.stripe
  %h2= "Issues in #{@search_language}"
- if @issues.present?
  .issue-list
    = render @issues, view: :index_language
- else
  .no-issues
    = "There don't seem to be any open issues for this language right now :("

app/views/languages/_language.html.haml
- case view
- when :badge_center
  %span.language-badge.center
    = language.name
- when :badge_left
  %span.language-badge.left
    = language.name

app/views/layouts/_footer.html.haml
#footer

  %ul
    %li Contact
    %li About
    %li FAQ

app/views/layouts/_navbar.html.haml
#navbar
  #logo
    %span.logo-image= link_to( image_tag('box_open.png', size: "40x40"), root_url)
    %span.logo-title= link_to("Start Open Source", root_url)
  %ul
    %li Contact
    %li About
    %li FAQ

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Startopensource</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>

<%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/projects/_project.html.haml
- case view
- when :index
  .project-listed 
    %h4.project-title= link_to project.name, project_path(project)
    %p= project.description
    = render project.languages, view: :badge_left

app/views/projects/index.html.haml
.stripe
  %h2= "Projects in #{@search_language}"
.project-list
  = render @projects, view: :index
    

app/views/projects/show.html.haml
- project ||= @project
.stripe
  %h2= project.name
.project
  .description
    %p= project.description
  .github
    %button.btn.btn-default
      = image_tag("octocat.png", size: "22x22")
      %span= "View on GitHub"
  .project-languages
    = render project.languages, view: :badge_center


  .issue-list
    = render @issues, view: :index_project